title: Henry Stanley
email: henry@henrystanley.com
# description:

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://henryaj.github.io"
twitter_username: henryaj
github_username:  henryaj

markdown: kramdown
theme: minima
