title: Henry Stanley
email: &email henry@henrystanley.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://henrystanley.com"
# twitter_username: henryaj
# github_username: henryaj

markdown: kramdown

paginate: 5

gems:
- jekyll-redirect-from

# About/contact
author:
  name:              Henry Stanley
  url:               http://henrystanley.com
  email:             *email

permalink: /:title/
