title: Arguably
email: henry@henrystanley.com
description: Shouting about stuff on the internet since 2004.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://henryaj.github.io"
twitter_username: henryaj
github_username: henryaj

markdown: kramdown
theme: minima
