title: Arguably
email: &email henry@henrystanley.com
description: &desc Shouting about stuff on the internet since 2004.
tagline: *desc

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://henrystanley.com"
# twitter_username: henryaj
# github_username: henryaj

markdown: kramdown

paginate: 5

# About/contact
author:
  name:              Henry Stanley
  url:               http://henrystanley.com
  email:             *email

permalink: /:title/
